title: Ruoqi Liu
position: Postdoctoral Researcher  
affiliation: Stanford University 
email: ruoqiliu@stanford.edu
keywords: Ruoqi Liu's homepage
google_scholar: https://scholar.google.com/citations?hl=en&user=bScV4D0AAAAJ&view_op=list_works&sortby=pubdate
github_link: https://github.com/ruoqi-liu/
linkedin: https://www.linkedin.com/in/ruoqi-liu/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Ruoqi Liu's homepage.
canonical: https://ruoqi-liu.github.io/
remote_theme: yaoyao-liu/minimal-light
